env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  comma-dangle:
    - error
    - always-multiline
  indent:
    - warn
    - 4
  quotes:
    - error
    - single
  no-unused-vars: warn
  semi:
    - error
    - never
settings:
  react:
    version: detect
